[package]
name = "bitcask_rs"
version = "0.1.0"
edition = "2021"
[[example]]
name="basic_operations"
path="./examples/basic_operations.rs"
[dependencies]
parking_lot="0.12.3"
log="0.4.0"
env_logger="0.11.3"
thiserror="1.0.38"
bytes = "1"
prost = "0.12.6"
crc32fast = "1.4.2"